### ISSUE TITLE
Standard library gems

### ISSUE THREAD

**Issue by valerie-makes** [anatol/quarry#23]
Often the standard library gems get updated between different Ruby releases, but not all of these gems are present in Quarry. The following gems are missing:

```
bigdecimal io-console power_assert psych test-unit
```

The ones that _are_ present for reference:

```
json minitest rake rdoc
```

Maybe there could be a metapackage or group to install all of these at once, e.g. `ruby-stdlib`

**Comment by tech4david** [comment]
See https://github.com/anatol/quarry/pull/24

**Comment by anatol** [comment]
Managing the same library as a separate package and part of other package (in this case ruby) is not that easy. There was Arch bug related to it https://bugs.archlinux.org/task/38411

I keep thinking that the best way to solve this issue is to ask ruby upstream to add possibility to ship ruby without bundled 'rubygems'. And ship this rubygems as a separate Arch package.
